### ISSUE TITLE
Docs issue on constraints based design page

### ISSUE THREAD

**Issue by anshuraj** [siddharthkp/react-ui#92] opened 2020-05-20 10:16 UTC
On [Constraints Based Design](https://react-ui.dev/core-concepts/constraints-based-design) page text becomes invisible on selecting dark theme.

![Screenshot 2020-05-20 at 3 42 03 PM](https://user-images.githubusercontent.com/4736201/82434625-c0ee8480-9ab0-11ea-93a2-ec977f7d4b5e.png)

**Comment by shubh0107** [comment] 2020-05-23 18:41
There's a `ThemeProvider` that wraps the Constraint page and has `token` and `components` props set to `light.tokens` and `light.components`. Removing it will fix this issue. 

Can i take this up ?

**Comment by siddharthkp** [comment] 2020-05-25 08:36
This is already a work in progress. Duplicate of https://github.com/siddharthkp/react-ui/issues/44

**Closed by siddharthkp** 2020-05-25 08:36 UTC
