### ISSUE TITLE
Demo theme switch

### ISSUE THREAD

**Issue by thewebsitedev** [siddharthkp/react-ui#3] opened 2020-03-18 17:42 UTC
Hi, I was just checking out the demo and found that switching to base theme and then to some other theme produces the attached error.
<img width="1050" alt="Screenshot 2020-03-18 at 11 10 00 PM" src="https://user-images.githubusercontent.com/4481867/76990366-ddb1f300-696d-11ea-9a6d-49de44ebe1d6.png">

**Comment by siddharthkp** [comment] 2020-03-19 09:49
Good catch! 

Would you like to create a pull request with a fix?

The files to look at are: https://github.com/siddharthkp/react-ui/blob/master/packages/docs/src/components/theme-switcher.js and https://github.com/siddharthkp/react-ui/blob/67d38a912deb142fe291e3a3dcc40e64f7e4ee78/packages/docs/src/App.js#L77

**Comment by thewebsitedev** [comment] 2020-03-21 08:34
I will give it a try tomorrow. Saturday is also a working day. :)

**Comment by themre** [comment] 2020-03-28 09:59
Hi, I tried to look at this problem, but have trouble running the project. When running docs, I get:
```
../react-ui/src/components/avatar/index.js
SyntaxError: {myPath}\react-ui\packages\react-ui\src\components\avatar\index.js: Unexpected token (8:2)

   6 | 
   7 | export const Avatar = ({ css, ...props }) => (
>  8 |   <Element
     |   ^
   9 |     as="img"
```
I'm on Windows, so maybe this could be the issue?

**Comment by anuraghazra** [comment] 2020-03-28 10:07
run `yarn build` on packages/react-ui

**Comment by themre** [comment] 2020-03-28 13:01
I still didn't find a good solution, the issue is in the `interpolate` function passed to `Global` component which apparently creates some change in the DOM that some node gets removed. Also a lot of warnings is thrown due to incorrect styles generation, e.g.:
```
blue is not a valid token for color in undefined component, applying "color: blue" as fallback. Please use one of the keys on the 'colors' scale.
```

**Comment by siddharthkp** [comment] 2020-03-28 21:05
Found the problem, fixed in https://github.com/siddharthkp/react-ui/commit/03053bfb32e82bbc4bf0300e4596962e174a7ffe

**Closed by siddharthkp** 2020-03-28 21:05 UTC
